repos:
  # --- General hygiene hooks ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ["--maxkb=1024"]

  # --- Terraform hooks ---
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.1
    hooks:
      - id: terraform_fmt
        args:
          - --args=-no-color
          - --args=-recursive
          - --args=-write=true
      - id: terraform_docs
        args: ["--hook-config=--path-to-file=README.md", "--hook-config=--add-to-existing-file=true", "--hook-config=--recursive"]
      - id: terraform_tflint
      - id: terraform_docs
        rev: v1.93.0
        hooks:
          - id: terraform_docs
            args:
              - --hook-config=--path-to-file=README.md
              - --hook-config=--add-to-existing-file=true
              - --hook-config=--create-file-if-not-exist=true
              - --hook-config=--use-standard-markers=true
