AWSTemplateFormatVersion: '2010-09-09'
Description: Git-synced Service Catalog product (SourceConnection → GitHub)

Parameters:
  ProductName:        { Type: String }
  ProductOwner:       { Type: String }
  ConnectionArn:      { Type: String }
  Repository:         { Type: String, Description: "org/repo" }
  Branch:             { Type: String }
  ArtifactPath:       { Type: String }
  PortfolioId:        { Type: String }
  LaunchRoleArn:      { Type: String, Default: "" }
  LaunchLocalRoleName: { Type: String, Default: "" }

Resources:
  Product:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name:        !Ref ProductName
      Owner:       !Ref ProductOwner
      ProductType: CLOUD_FORMATION_TEMPLATE
      SourceConnection:
        Type: CODESTAR
        ConnectionParameters:
          CodeStar:
            ConnectionArn: !Ref ConnectionArn
            Repository:    !Ref Repository
            Branch:        !Ref Branch
            ArtifactPath:  !Ref ArtifactPath

  Assoc:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !Ref PortfolioId
      ProductId:   !Ref Product

Outputs:
  ProductId:   { Value: !Ref Product }
  ProductName: { Value: !GetAtt Product.ProductName }
